#!/usr/bin/env ruby
# -*- coding: utf-8; mode: ruby -*-

## Settings
#--------------------
# SERVER (host and port with "ws" protocol)
SERVER = "ws://127.0.0.1:51234"
#--------------------


$: << File.expand_path(File.dirname(__FILE__))

require 'lib/web-socket-ruby/lib/web_socket'

argv = ARGV
if argv.size <= 0
  puts "Please enter your username."
  exit()
end

username = ARGV[0]
unless username =~ /^[a-zA-Z0-9]+$/
  puts "Required username is [a-zA-Z0-9]"
  exit()
end


# クライアント
client = WebSocket.new(SERVER)
client.send("@username: #{username}")

Thread.new() do
  while data = client.receive()
    puts data
  end
  exit()
end

$stdin.each_line() do |line|
  data = line.chomp()
  if data == 'exit'
    client.close()
    exit()
  else
    client.send(data)
  end
end

client.close()
